# /********************************************************************************
# * Copyright (c) 2023 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Apache License 2.0 which is available at
# * http://www.apache.org/licenses/LICENSE-2.0
# *
# * SPDX-License-Identifier: Apache-2.0
# ********************************************************************************/
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

# This configures Dependabot version updates, to keep dependencies up to date.
# Dependabot security updates are configured differently,
# see: https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/about-dependabot-security-updates

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/kuksa-client"
    schedule:
      interval: "monthly"

  # Will hopefully include all referenced *.toml files as well
  # If not we may to include them manually
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      
  - package-ecosystem: "gomod"
    directory: "/kuksa_go_client"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/kuksa-client"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/kuksa_databroker"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/kuksa-val-server/docker"
    schedule:
      interval: "monthly"
